# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0002_pessoa_papel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(help_text='Breve descricao da tarefa')),
                ('resposta', models.TextField(help_text='Resposta sobre a execu\xe7\xe3o da tarefa')),
                ('data_previsao', models.DateTimeField(help_text='Data prevista para conclus\xe3o da tarefa')),
                ('data_inicio', models.DateTimeField(help_text='Quando a tarefa foi iniciada')),
                ('data_fim', models.DateTimeField(help_text='Quando a tarefa foi concluida')),
                ('excluido', models.BooleanField(help_text='Marque esta op\xe7\xe3o se quiser excluir a tarefa. Tarefa deixar\xe1 de ser contabilizada')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Fase')),
                ('projeto', models.ForeignKey(help_text='Projeto ao qual a tarefa deve ser aplicada', on_delete=django.db.models.deletion.CASCADE, to='comum.Projeto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Responsavel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Status')),
            ],
        ),
    ]
