# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='fase',
        ),
    ]
