# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descri\xe7\xe3o do que o comando deve executar', max_length=120)),
                ('command', models.TextField(help_text='Comando a ser executado pelo cron')),
                ('data_inicio', models.DateTimeField(help_text='Quando o comando deve ser rodado')),
                ('repetir', models.BooleanField(help_text='O comando deve ser repetido?')),
                ('repeticoes', models.IntegerField(help_text='Caso o comando seja recorrente, quantas vezes o comando deve rodar?')),
                ('frequencia', models.CharField(choices=[('SEGUNDOS', 'SEGUNDOS'), ('MINUTOS', 'MINUTOS'), ('HORAS', 'HORAS'), ('DIAS', 'DIAS'), ('SEMANAS', 'SEMANAS'), ('MESES', 'MESES')], help_text='Periodicidade do comando a ser executado', max_length=128)),
                ('excluido', models.BooleanField(help_text='Excluir atividade agendada')),
                ('responsavel', models.ForeignKey(help_text='Respons\xe1vel pela tarefa agendada', on_delete=django.db.models.deletion.CASCADE, to='comum.Responsavel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('data_inicio', models.DateTimeField(help_text='Data in\xedcio do cronograma')),
                ('data_fim', models.DateTimeField(help_text='Data final do cronograma')),
                ('excluido', models.BooleanField(help_text='Excluir cronograma. Cronogramas excluido n\xe3o s\xe3o considerados')),
                ('projeto', models.ForeignKey(help_text='Projeto para o qual este cronograma ser\xe1 aplicado', on_delete=django.db.models.deletion.CASCADE, to='comum.Projeto')),
                ('status', models.ForeignKey(help_text='Em que status este cronograma se encontrada', on_delete=django.db.models.deletion.CASCADE, to='comum.Status')),
            ],
        ),
    ]
