# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0003_basesdedados_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('SEGUNDOS', 'SEGUNDOS'), ('MINUTOS', 'MINUTOS'), ('HORAS', 'HORAS'), ('DIAS', 'DIAS'), ('SEMANAS', 'SEMANAS'), ('MESES', 'MESES')], help_text='Periodicidade do comando a ser executado', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cron',
            name='repeticoes',
            field=models.IntegerField(blank=True, help_text='Caso o comando seja recorrente, quantas vezes o comando deve rodar?', null=True),
        ),
    ]
