# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0004_auto_20160329_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descreva o objetivo e breve funcionamento do bot')),
                ('arquivo', models.FileField(upload_to='uploads/bots/')),
            ],
        ),
        migrations.AddField(
            model_name='cron',
            name='bot',
            field=models.ForeignKey(blank=True, help_text='Selecione o script que deve rodar', null=True, on_delete=django.db.models.deletion.CASCADE, to='cron.Bot'),
        ),
    ]
