# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0005_auto_20160615_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cron',
            old_name='frequencia',
            new_name='periodicidade',
        ),
        migrations.RemoveField(
            model_name='cron',
            name='commando',
        ),
        migrations.AddField(
            model_name='cron',
            name='codigo_a_rodar',
            field=models.TextField(blank=True, help_text='C\xf3digo a ser executado pelo Agendador', null=True),
        ),
        migrations.AddField(
            model_name='cron',
            name='repetir_a_cada',
            field=models.IntegerField(blank=True, help_text='A cada quanto tempo o comando deve ser repetido', null=True),
        ),
        migrations.AddField(
            model_name='cron',
            name='tipo_codigo',
            field=models.CharField(choices=[('SCRIPT SHELL', 'SHELL'), ('SCRIPT PYTHON', 'PYTHON')], default='Python', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cron',
            name='base_de_dados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cron.BasesDeDados'),
        ),
        migrations.AlterField(
            model_name='cron',
            name='bot',
            field=models.ForeignKey(blank=True, help_text='Selecione e suba o script que deve rodar', null=True, on_delete=django.db.models.deletion.CASCADE, to='cron.Bot'),
        ),
        migrations.AlterField(
            model_name='cron',
            name='data_inicio',
            field=models.DateTimeField(help_text='Quando o comando deve ser rodado?'),
        ),
        migrations.AlterField(
            model_name='cron',
            name='status',
            field=models.CharField(choices=[('HABILITADO', 'HABILITADO'), ('DESABILITADO', 'DESABILITADO')], max_length=128),
        ),
    ]
