# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0006_auto_20160620_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron',
            name='problemas',
            field=models.TextField(blank=True, help_text='Possiveis problemas com a tarefa', null=True),
        ),
        migrations.AddField(
            model_name='cron',
            name='sucesso',
            field=models.NullBooleanField(help_text='Se a tarefa foi executada com sucesso pelo Agendador'),
        ),
        migrations.AlterField(
            model_name='cron',
            name='base_de_dados',
            field=models.ForeignKey(blank=True, help_text='EXPERIMENTAL: N\xc3O IMPLEMENTADO AINDA.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cron.BasesDeDados'),
        ),
        migrations.AlterField(
            model_name='cron',
            name='codigo_a_rodar',
            field=models.TextField(blank=True, help_text='C\xf3digo a ser executado pelo Agendador. EXPERIMENTAL: N\xc3O IMPLEMENTADO AINDA!', null=True),
        ),
        migrations.AlterField(
            model_name='cron',
            name='tipo_codigo',
            field=models.CharField(choices=[('SHELL', 'SHELL'), ('PYTHON', 'PYTHON')], max_length=128),
        ),
    ]
