# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0007_auto_20160620_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='cron',
            name='saida',
            field=models.TextField(blank=True, help_text='Saida do comando/script executado', null=True),
        ),
    ]
