# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('excluido', models.BooleanField(help_text='Marque esta op\xe7\xe3o se quiser excluir o item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('excluido', models.BooleanField(help_text='Marque esta op\xe7\xe3o se quiser excluir o item')),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Pap\xe9is',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('excluido', models.BooleanField(help_text='Marque esta op\xe7\xe3o se quiser excluir o item')),
                ('email', models.EmailField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('excluido', models.BooleanField(help_text='Marque esta op\xe7\xe3o se quiser excluir o item')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Fase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=256)),
                ('cargo', models.CharField(max_length=120)),
                ('excluido', models.BooleanField(help_text='Marque esta op\xe7\xe3o se quiser excluir o responsavel')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Papel')),
            ],
            options={
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Respons\xe1veis',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('excluido', models.BooleanField(help_text='Marque esta op\xe7\xe3o se quiser excluir o item')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('excluido', models.BooleanField(help_text='Marque esta op\xe7\xe3o se quiser excluir o item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Responsavel'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Pessoa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.Status'),
        ),
    ]
