# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='papel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comum.Papel'),
            preserve_default=False,
        ),
    ]
