# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_pessoa_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='matricula',
            field=models.CharField(default='-', max_length=120),
            preserve_default=False,
        ),
    ]
