# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_responsavel_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='papel',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comum.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='comum.Responsavel'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='matricula',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
