# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_auto_20160310_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='status',
        ),
    ]
