# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0006_auto_20160311_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentacao',
            options={'verbose_name': 'Documenta\xe7\xe3o', 'verbose_name_plural': 'Documenta\xe7\xf5es'},
        ),
    ]
