# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0007_auto_20160311_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('excluido', models.BooleanField(help_text='Marque esta op\xe7\xe3o se quiser excluir o item')),
                ('integrante', models.ManyToManyField(to='comum.Responsavel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
