# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0008_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacao',
            name='slug',
            field=models.CharField(default='_', max_length=240),
        ),
        migrations.AddField(
            model_name='equipe',
            name='slug',
            field=models.CharField(default='_', max_length=240),
        ),
        migrations.AddField(
            model_name='fase',
            name='slug',
            field=models.CharField(default='_', max_length=240),
        ),
        migrations.AddField(
            model_name='midia',
            name='slug',
            field=models.CharField(default='_', max_length=240),
        ),
        migrations.AddField(
            model_name='papel',
            name='slug',
            field=models.CharField(default='_', max_length=240),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='slug',
            field=models.CharField(default='_', max_length=240),
        ),
        migrations.AddField(
            model_name='projeto',
            name='slug',
            field=models.CharField(default='_', max_length=240),
        ),
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.CharField(default='_', max_length=240),
        ),
        migrations.AddField(
            model_name='tipo',
            name='slug',
            field=models.CharField(default='_', max_length=240),
        ),
    ]
