# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0009_auto_20160329_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentacao',
            name='slug',
            field=models.CharField(blank=True, default='_', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='slug',
            field=models.CharField(blank=True, default='_', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='fase',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fase',
            name='slug',
            field=models.CharField(blank=True, default='_', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='midia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midia',
            name='slug',
            field=models.CharField(blank=True, default='_', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='papel',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='papel',
            name='slug',
            field=models.CharField(blank=True, default='_', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='slug',
            field=models.CharField(blank=True, default='_', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='slug',
            field=models.CharField(blank=True, default='_', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='slug',
            field=models.CharField(blank=True, default='_', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='slug',
            field=models.CharField(blank=True, default='_', max_length=240, null=True),
        ),
    ]
